version: '2'
services:
  app:
    image: com.thedeveloperhive/spring-boot-zipkin-sleuth-splunk
    environment:
      - LOGGING_FILE=/logs/app.log
    ports:
      - "8080:8080"
    volumes:
      - log_volume:/logs
  splunk:
    image: splunk/splunk
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
  splunkforwarder:
    image: splunk/universalforwarder:6.5.3-monitor
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_FORWARD_SERVER=splunk:9997
      - SPLUNK_ADD=monitor /logs
      - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      - splunk
    volumes:
      - log_volume:/logs
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
volumes:
  log_volume:
